worker_processes auto;
events { worker_connections 1024; }

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 80;
        root /var/www/html/public;
        index index.php;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location /build/ {
            try_files $uri =404;
            access_log off;
            expires 1y;
            add_header Cache-Control "public, immutable";
        }

        location ~ \.php$ {
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
            fastcgi_param HTTPS on;
            fastcgi_param HTTP_X_FORWARDED_PROTO $http_x_forwarded_proto;
            fastcgi_param HTTP_X_FORWARDED_HOST $http_x_forwarded_host;
            fastcgi_param HTTP_X_FORWARDED_PORT $http_x_forwarded_port;
            include fastcgi_params;
        }

        location ~ /\.ht {
            deny all;
        }
    }
}
